### ISSUE TITLE
Broken links.

### ISSUE THREAD

**Issue by Houlistonm** [cloudfoundry/cf-networking-onboarding#2]
The file `cf-networking-onboarding/c2c/070-dataflow-pt-3.markdown` has links to `silk-release` that are broken due to reorganization of the silk-release repo.  Not knowing exactly what they once pointed to, it's difficult to suggest new links.

Suggestion -  Add github action to check for broken links.

**Comment by ameowlia** [comment]
Thanks for pointing this out!
